### ISSUE TITLE
PHP8.0 -> PHP8.1

### ISSUE THREAD

**Issue by atomisfat** [Yanik39/TORNet#5]
Hello.
Most of the configurations files are pointing to the old 8.0 directories. (Supervisor, torlog, etc)

I've fixed the ones I could on my own build, but after it has been fixed, a new problem appears.

Neither TOR or DNSMASQ will start properly any longer.
Running on Debian 11 Bullseye

Take care, thanks.

**Comment by Yanik39** [comment]
Hi,
I fixed all and with new image everything starts perfectly.
Please be sure you are using latest development image.
Will publish new version after few tests.

**Comment by atomisfat** [comment]
Okay, thanks for the quick updates.

I have noticed one more thing, which I cannot seem to patch.
php connection to mysql/mariadb is not working at all - either it's permission denied or connection refused.

Have created new user accounts in database & given priviliges.
You got any ideas?

**Comment by atomisfat** [comment]
@Yanik39, I still cannot connect to the local MySQL/MariaDB from my PHP Script.
You have any ideas at all? Feels like i've tried everything almost.

**Comment by atomisfat** [comment]
bump? @Yanik39

**Comment by Yanik39** [comment]
Sunday i can do some test. Sorry for late response.

**Comment by Yanik39** [comment]
@atomisfat Which php script are you using? or some custom script?

**Comment by atomisfat** [comment]
@Yanik39 do you have a private contact info, like telegram or such.

Am just testing with basic PHP MYSQL connection. 
I'll try again now, just gimme a couple minutes and ill reply back on thread brother.

**Comment by Yanik39** [comment]
For connection are you using socket right? mysqld listening on socket.
To test; https://gist.github.com/chales/11359952
